spring:
  api:
    key:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
        provider:
          custom-google:
            issuer-uri:
  logging:
    level:
      org.springframework.web.client.RestTemplate: DEBUG
      org.springframework.kafka: TRACE,stdout

  data:
    mongodb:
      uri:
      database:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      bootstrap.servers: localhost:9092

      session.timeout.ms: 45000
      acks: all
